### ISSUE TITLE
Convert HapMap 

### ISSUE THREAD

**Issue by snowformatics** [maize-genetics/rTASSEL#1]
Hi,

Quick question, is it possible to use rtassel to convert HapMap to vcf or plink format?

Thanks

**Comment by btmonier** [comment]
Hello,

Yes, `rTASSEL` can be used to convert between several commonly used genotype data formats. Here is an example using the method `exportGenotypeTable()`:

``` r
library(magrittr)

## Load HapMap toy data from `rTASSEL` package ----
genoPathHMP <- system.file(
    "extdata",
    "mdp_genotype.hmp.txt",
    package = "rTASSEL"
)

myGenoTable <- readGenotypeTableFromPath(path = genoPathHMP)


## Export as VCF data ----
myGenoTable %>% exportGenotypeTable(file = "my_geno_info.vcf", format = "vcf")
```

For more information about exporting to other file types, please visit this page:
https://maize-genetics.github.io/rTASSEL/reference/exportGenotypeTable.html

Cheers,
Brandon M.
