### ISSUE TITLE
Error while using readGenotypeTableFromPath()

### ISSUE THREAD

**Issue by robolvhez** [maize-genetics/rTASSEL#13]
Hi!
Currently I'm having problems while loading my **genotype file**.

This is the command that I'm using:
```{r}
genoPathHMP <- "data/genotype_dmz119.hmp.txt"
tasGenoHMP <- rTASSEL::readGenotypeTableFromPath(
    path = genoPathHMP
)
```

And the error in console states:
```{shell}
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.IllegalStateException: ImportUtils: read: nothing was loaded for: data/genotype_dmz119.hmp.txt
```

- File works fine in TASSEL 5.0 GUI.
- Dummy file from [documentation](https://rtassel.maizegenetics.net/articles/rtassel_walkthrough.html#loading-genotype-data) worksfine.
- Eliminated every special character for taxa or SNP ID.
- Working directory is the same as root of RProject.

**Comment by btmonier** [comment]
Hi Roberto,

Thanks for checking out rTASSEL. What happens when you specify the `sortPositions` parameter to `TRUE`?

For example:

``` R
genoPathHMP <- "data/genotype_dmz119.hmp.txt"
tasGenoHMP <- rTASSEL::readGenotypeTableFromPath(
    path = genoPathHMP,
    sortPositions = TRUE
)
```

**Comment by robolvhez** [comment]
Worked perfectly! Thanks
